### PR TITLE
Add frontEnd file strcuture

### PR DESCRIPTION
**Pull request by Brackleycassinga**

### CODE REVIEW

**Review by bvenceslas — COMMENTED** [review]
Add a label so that we may see the progress, please

**Comment by Brackleycassinga** [comment]
I have added a progress label.Thanks

**Comment by bvenceslas** [comment]
> I have added a progress label.Thanks

Good!

**Comment by Brackleycassinga** [comment]
This need to be closed as all the code has been merged in my recent PR.

**Pull request closed without merging**
